"""add clean_sheets to player

Revision ID: 2e3cffd67e36
Revises: ad3d1f8d6366
Create Date: 2026-02-14 20:44:03.146626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3cffd67e36'
down_revision = 'ad3d1f8d6366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clean_sheets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('clean_sheets')

    # ### end Alembic commands ###
